### ISSUE TITLE
Pointer renderer lags behind its controller

### ISSUE THREAD

**Issue by ajonsacc** [thestonefox/VRTK#1394] opened 2017-07-31 12:35 UTC
### Environment

 * Source of VRTK: github release
 * Version of VRTK: alpha 3.3.0 (github 6c8342e71615b4baabf8a5ca9dde50656b6932be)
 * Version of Unity3D: 5.6.1f1
 * Hardware used: GearVR with S6 phone, and a mac
 * SDK: Oculus Utilities (GearVR) and Simulator SDK in Unity on mac

### Steps to reproduce

1. Open example scene 003.
2. In [VRTK_Scripts]/RightController, set VRTK_StraightPointerRenderer "Activate On Enable" to true. 
3. Play using Simulator SDK. 

### Expected behavior

The pointer renderer should follow the controller without lag when moved around, as if it was attached to it.

### Current behavior

The rendered pointer is lagging behind.

Not sure if this also applies to the VRTK_Pointer class, i.e when moving around controller and triggering InteractableObjectTouched on interactables. Hard to test.

I tried setting timestamp to 0.01111111, but it is still not perfectly following controller. 

@bddckr on Slack looked into it quickly, and says "Yeah it's the transform follow that is being used. Needs a VRTK change in VRTK_BasePointerRenderer. I tried all the different TransformFollow.moment settings, but for some reason it's always lagging behind."

**Comment by bddckr** [comment] 2017-07-31 12:55
Hopefully we can find a non-laggy solution so Transform/RigidbodyFollow don't lag.

**Comment by thestonefox** [comment] 2017-08-01 10:37
They probably will always lag in 5.6 and previous. Doesn't Unity 2017 have a new stage where it can perform updates? Maybe that new state would reduce the lag?

**Comment by bddckr** [comment] 2017-08-01 12:05
Good idea, I will try that later.

**Comment by thestonefox** [comment] 2017-08-08 16:42
This doesn't happen for vive and rift. Could it be to do with how the simulator updates its position?

**Comment by bddckr** [comment] 2017-08-08 17:21
😮 Yes, yes of course! Did you try with GearVR, too, as that is what is named in the issue report, too?

**Comment by thestonefox** [comment] 2017-08-08 17:25
I'll try on GearVR

**Comment by thestonefox** [comment] 2017-08-10 10:24
Confirmed it does it in GearVR as well

**Comment by thestonefox** [comment] 2017-08-10 10:57
FYI @bddckr the pointers don't use the transform follow stuff, they just set the position within `Update`

But moving to `FixedUpdate` doesn't fix things either

**Comment by thestonefox** [comment] 2017-08-10 12:03
@bddckr so the issue seems to be that when the position of the beam is updated it's doing a `GetOrigin()` call which always returns the smoothing game object (because `smoothed = true` is default).

If I do `GetOrigin(false)` then it works because it's always updating against the actual right controller object, not the smoothed object.

But I'm not entirely sure how this smoothed object works, it seems to always return the Smoothed Object for origin at the moment because all instances of `GetOrigin()` don't pass a param so it's always set to `true` which means smoothing is always being applied (which is not expected?)

**Comment by bddckr** [comment] 2017-08-10 12:29
`GetOrigin(false)` *is* used already, only in the places that need the unsmoothed position at all times,
`GetOrigin(true)` needs to be used basically everywhere, what we currently should be doing is not relying on TransformFollow _at all_ if no smoothing is requested.

This whole code needs a refactor 😞

**Comment by thestonefox** [comment] 2017-08-10 12:46
@bddckr yeah I see what it does now, it always follows that origin, but then that origin (the smoothing object) will only have smoothing turned on if you turn it on within the pointer component.

But the problem is when pointer container follows the smoothing object (even without  smoothing applied) then it lags. If you get the pointer container to follow the actual controller object then no lag occurs.

**Comment by bddckr** [comment] 2017-08-10 12:48
I tried the various `TransformFollow.moment`s (by changing the code in the base pointer renderer IIRC) but that didn't fix the lag.

**Comment by thestonefox** [comment] 2017-08-10 12:51
I think the transform follow helper object actually tracks ok. If you child the pointer container to the object helper object then it works just fine.

The problem lies when there is a pointer container being updated to the position of the follow helper which is being updated to the position of the actual controller.

Actually why can't we just child the object?

**Comment by bddckr** [comment] 2017-08-10 12:52
We only need to make sure the smoothed object in a separate hierarchy chain compared to the one it's following, the rest I don't know about... 😅

**Comment by thestonefox** [comment] 2017-08-10 13:22
Lemme have a play with just childing the pointer container to the smoothed object. Because afaik it's always being set to get the origin of that object anyway. Is there ever a case where that object wouldn't exist?

**Comment by bddckr** [comment] 2017-08-10 13:25
🤷‍♂️ Can't remember.

**Comment by thestonefox** [comment] 2017-08-10 17:44
PR with proposed fix: https://github.com/thestonefox/VRTK/pull/1413

**Closed** 2017-08-11 09:35 UTC
Labels: bug, in review
