### ISSUE TITLE
[Camera Rig ] automatically changes layer to Ignore raycast.

### ISSUE THREAD

**Issue by MarkTheLily** [thestonefox/VRTK#759] opened 2016-12-21 16:35 UTC
I use VRTK_climbing and VRTK_heightadjustment.
When I start the game the [Camera rig] changes from Default layer to Ignore Raycast.
Does anyone know how keep it in default layer? So it will be affected by raycast from npcs
I'm pretty sure Player_Presence is doing it.

**Comment by thestonefox** [comment] 2016-12-21 16:37
duplicate of https://github.com/thestonefox/VRTK/issues/543

**Closed by thestonefox** 2016-12-21 16:37 UTC
Labels: duplicate
