### ISSUE TITLE
VRTK_SnapDropZone.ForceSnap

### ISSUE THREAD

**Issue by Anton-Tril** [thestonefox/VRTK#1044] opened 2017-03-21 17:31 UTC
If snapped object does not have the collider on its root gameobject this code will not work:
        protected virtual void OnTriggerStay(Collider collider)
        {
....
            //if (currentValidSnapObject == collider.gameObject) // will not work
            if (currentValidSnapObject != null && currentValidSnapObject.GetComponentsInChildren<Collider>().Contains(collider)) // <<<<<<<<<<<< fix

**Comment by thestonefox** [comment] 2017-03-22 13:55
I don't understand what you're saying the issue is.

Could you provide clear steps to reproduce in one of the example scenes.

**Comment by Anton-Tril** [comment] 2017-03-22 19:11
Sure
1. Create e.g. LightBulb prefab with RigidBody and MeshRenderer on root gameobject and few colliders on child gameobjcts (so no colliders on root)
2. Try to insert instance of LightBulb into socket on scene start (I assume that VRTK_SnapDropZone.ForceSnap should be used for that)
3. Nothing happens, because it inserts forced snap object to a snap zone

**Comment by thestonefox** [comment] 2017-03-23 10:13
Fixed with https://github.com/thestonefox/VRTK/commit/0bce6c3ada7413a193a2bf340355413d34428413

**Closed by thestonefox** 2017-03-23 10:13 UTC
