### ISSUE TITLE
VRTK Wheel

### ISSUE THREAD

**Issue by malakdecaen** [thestonefox/VRTK#1705] opened 2018-01-18 07:01 UTC
Knob script used for wheel work when it doesn't move but if you put in child of moving object it doesn't react anymore .

**Comment by bddckr** [comment] 2018-01-18 13:02
GitHub auto-filled an issue template for you to use. Since you didn't we have no steps to reproduce this in any example scene. You also didn't list any of the needed version information.

I suggest to try your luck asking this question in [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) instead.

@thestonefox I'm voting to close this.

**Comment by thestonefox** [comment] 2018-01-18 13:03
Plus VRTK_Wheel is deprecated in 3.3.0 so it's no longer supported.

**Closed by thestonefox** 2018-01-18 13:03 UTC
