### ISSUE TITLE
Interacting With UI Bug

### ISSUE THREAD

**Issue by maxkofford** [thestonefox/VRTK#787] opened 2017-01-05 18:13 UTC
Ive noticed a bug where if a Vive controller loses tracking for enough time (enough time for the controller to stop being moved around in-scene) it stops being able to interact with UI ever again (even if it starts tracking again).  You can replicate it by opening the example 34_Controls_InteractingWithUnityUI and then putting the controller out of view of the tracking stations for about 10 seconds.  After returning the controller back to the play area, it successfully starts tracking again and can interact with objects but it cant interact with UI menus any more.  An easier way to replicate this is just to run the scene and deactivate the controller in the inspector window and then reactivate it.   Before deactivation it works, after reactivation it does not work on UI menus.

**Comment by thestonefox** [comment] 2017-01-05 20:34
What version of vrtk are you using?

The one from the unity asset store or the latest master from github?

**Comment by maxkofford** [comment] 2017-01-05 20:57
The test project i was using just had SteamVR and the latest master in unity 5.50f3.  It doesnt happen every single time the controller loses tracking though (although setting the controller inactive and then reactivating it seems to trigger it every time). Also no errors are being thrown that i can see.  Debugging different parts of it indicate its something to do with the event system.  After the bug, the Process method on VRTK_EventSystemVRInput stops being called for some reason but before the bug its called often.

**Comment by thestonefox** [comment] 2017-01-05 20:59
but what version of VRTK are you using?

**Comment by maxkofford** [comment] 2017-01-05 21:06
Where do i check the version?  The one i tested on the first time i downloaded a couple months ago but i tested it today on the download as zip on the main page for the repo and then copied it into my project and tested it again and the bug still happens.

**Comment by thestonefox** [comment] 2017-01-05 21:09
if you've downloaded from github master then that's the latest version.

I've tried to recreate it in the example scene and I can't get it to fail even after disabling the controller game object.

Maybe someone else reading this issue can try too?

**Comment by maxkofford** [comment] 2017-01-05 21:14
Ah i just tested it in unity 5.4.3f1 and it doesnt show up in that one.  Maybe its just the version of unity I was on. Im going to download the newest version of unity and see if it appears in that one.

**Comment by thestonefox** [comment] 2017-01-05 21:15
I'm using unity 5.4 as well, maybe it's an issue with 5.5. I'll check in 5.5 and see

**Comment by maxkofford** [comment] 2017-01-05 23:55
Running it in the 5.6.0b3beta build on my computer also has it.

**Comment by thestonefox** [comment] 2017-01-06 08:23
I can confirm it doesn't work for me in unity 5.5

(unity 5.6 isn't supported yet as it's still in beta)

**Comment by thestonefox** [comment] 2017-01-06 10:04
Ok it seems to be an issue with Unity 5.5 when you lose focus on the game window, the `Process` method in a `BaseInputModule` is no longer called until you re-focus the game window.

So to try this out.

Do what you've been doing where you disable the UIPointer and then re-enable the script and then click back on the `Game` tab in unity to regain focus.

You should see the UIPointer works again.

Simply clicking out of the game tab is enough to stop the `Process` method from being called it seems.

**Comment by maxkofford** [comment] 2017-01-06 17:23
Ah yea doing what you said works.  I tried it out in a build to see if the focus problem happens when you dont have the editor and it does. If you lose focus on the app by selecting another program on the desktop the menu input stops working.  I guess the work around is something like detecting that the app has lost focus and then somehow detect the user is trying to use a menu and force the focus back to the app.   I guess this means that you cant have someone using the desktop as the same time as someone is using the vive.

**Comment by thestonefox** [comment] 2017-01-06 17:25
The issue is due to Unity introducing a new (stupid) feature into 5.5. where the event system pauses if you lose focus.

We're working on a fix to work around this so it still works. i'll keep you posted! :)

**Comment by maxkofford** [comment] 2017-01-06 17:26
Thanks!

**Comment by thestonefox** [comment] 2017-01-06 19:18
PR to attempt at fixing issue: https://github.com/thestonefox/VRTK/pull/792

**Comment by maxkofford** [comment] 2017-01-06 19:37
Nice! Seems to work great on my end.

**Comment by thestonefox** [comment] 2017-01-06 19:38
Fixed with https://github.com/thestonefox/VRTK/commit/1a3328f78b8f86763bcefad9ae6269cf1dd70f31

**Closed by thestonefox** 2017-01-06 19:38 UTC
