### ISSUE TITLE
OnTouch / Untouch emitted on every frame when Collider in Child object

### ISSUE THREAD

**Issue by spaggi2** [thestonefox/VRTK#983] opened 2017-03-05 07:19 UTC
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Both, Git from around end of Feb
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.1.0
 * Version of Unity3D (e.g. Unity 5.4.4f1)
5.5.0f3

### Steps to reproduce

- Open up 041_Controller_ObjectSnappingToDropZones
- Select the Object "OtherSaucer_HightlightOnTouch"
- Remove the Box Collider from the GameObject "OtherSaucer_HightlightOnTouch" DO NOT remove the Collider from the Child object "Capsule"
- Add the following script for debugging purposes (sorry I don't know why the formatting is messed up here)

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using VRTK;

public class Testi : MonoBehaviour {

	// Use this for initialization
	void Start () {
        GetComponent<VRTK_InteractableObject>().InteractableObjectTouched += onTouch;
        GetComponent<VRTK_InteractableObject>().InteractableObjectUntouched += onUntouch;

    }
	

    void onTouch(object sender, InteractableObjectEventArgs e)
    {
        Debug.Log("Touch VRTK");
    }

    void onUntouch(object sender, InteractableObjectEventArgs e)
    {
        Debug.Log("Untouch VRTK");
    }

    void OnTriggerEnter(Collider other)
    {
        Debug.Log("Touch Unity");
    }
}
`

### Expected behavior

When touching the object, there should be one Log entry "Touch VRTK", when Untouching one entry "Untouch VRTK". This is what happens when there's a box collider on the parent object

### Current behavior

There is one event "OnTouch" and one "OnUntouch" emitted in every frame, making these events not usable.

The OnTriggerEnter emits one event as espected

**Comment by thestonefox** [comment] 2017-03-05 23:03
I think i have a fix for this.

in `VRTK_InteractTouch` on line 242

Replace with:

`if (touchedObject == null || collider.transform.IsChildOf(touchedObject.transform))`

That seems to work in my initial tests.

**Comment by spaggi2** [comment] 2017-03-06 05:39
Hi, thanks a lot, but it's not fully clear for me.

Line 242 is currently 

` var colliderInteractableObject = TriggerStart(collider);`

Line 244 is

`if (touchedObject == null || touchedObject == collider.gameObject)`

I assume that's the one right?

**Comment by thestonefox** [comment] 2017-03-06 15:03
Fixed with https://github.com/thestonefox/VRTK/commit/fccddb6565d6f7b4ae28d8c56535c2d4505a3275

**Closed by thestonefox** 2017-03-06 15:03 UTC
Labels: bug, in progress

**Comment by blackmoron** [comment] 2018-01-10 13:25
This fix caused/revealed another bug... When you got a hierarchy of objects such as Go1 -> Go2 ->Go3 -> Go4 OnTouch will be triggered on wrong Go, se attached video. When I move the controller from Go2 to Go3 (note that controller is still colliding with something) the Go2 is still highlighted because OnTouch was called on Go2 instead of Go3.

[video](https://drive.google.com/file/d/17jsE5VrRG9ly7LSSKr2esXXvHdovtJ43/view?usp=sharing)

**Comment by thestonefox** [comment] 2018-01-10 13:28
you will need to raise a new issue with steps to reproduce in an example scene.
