### ISSUE TITLE
Bezier Pointer "Flickers" When Far from Origin

### ISSUE THREAD

**Issue by Exguardi** [thestonefox/VRTK#846] opened 2017-01-20 02:59 UTC
Steps to reproduce:
1) Open 020_CameraRig_MeshTeleporting
2) Move [CameraRig] to (195, 442.71, 90) and cliff (1) to (195, 442.71, 99.74)
3) Observe that the bezier pointer "flickers" rapidly between valid/invalid teleport when pointed at most parts of the cliff object

**Comment by bddckr** [comment] 2017-01-20 14:23
It looks like the issue is the mesh collider on `cliff (1)`. If you disable that collider and add a child object to `cliff (1)` with just a box collider on it it works fine.

If you debug print `VRTK_BezierPointer.ProjectDownBeam` you'll see that it is switching between `(196.0, 444.1, 97.4)` and `(195.9, 0.0, 97.4)`.

So my guess is: The small shakes one does when holding the controllers are enough to actually let the raycasts hit the ground on that mesh collider. Maybe #796 helps with this.
The mesh (collider) probably just needs to be improved to remove the sharp ascents.

**Comment by Exguardi** [comment] 2017-01-20 17:53
The odd thing is that I don't see this issue if both the player and the mesh collider are close to the scene origin. If you just use the 020_CameraRig_MeshTeleporting scene as-is the bezier pointer works fine on the cliff geo.

**Comment by bddckr** [comment] 2017-01-20 17:58
Yup, no idea why it's doing it only at a high distance from the origin. Maybe some kind of precision issue with the raycasts?

**Comment by Exguardi** [comment] 2017-01-20 18:14
The smoothing is nice but does not help; also, in order to fix errors when merging the smoothing I had to modify line 106 of SDK_OculusVRBoundaries like so:
`objectFollow.gameObjectToFollow = GetPlayArea().gameObject;`

And line 564 in VRTK_BasePointer to:
`if (pointerOriginTransformFollowGameObject != null)
            {
                pointerOriginTransformFollowGameObject.SetActive(false);
            }`

**Comment by bddckr** [comment] 2017-01-21 11:01
Thanks for the fixes for the smoothing PR, I'll merge them into the PR.

As for the original issue: If you move the terrain up to `y=442.71`, too, you'll see that the flickering reduces. The same flickering is visible when everything is set to `y=0` as in the original example scene.

I guess this means that the flickering is only more visible when moving them far above the terrain because the pointer cursor is switching between `0` and `442.71` in different frames. Switching between something like `0` and `5` does not make the flicker that visible.
I still think the cliff's slopes are the problem here.

**Comment by Exguardi** [comment] 2017-01-23 18:54
Fyi, bddckr, it seems that the Oculus Avatar SDK is not compatible with the smooth pointer changes. It complains about being unable to attach an abstract class ObjectFollow; I attempted to fix the issue but could not get the controllers to properly follow the camera rig.

I've also been unable to determine how to resolve this "flickering" issue; it does not appear to have anything to do with the mesh slope as far as I can tell, if I use a relatively "flat" mesh the same problem occurs the second I get decently far away from the origin.

**Comment by bddckr** [comment] 2017-01-23 19:22
> Fyi, bddckr, it seems that the Oculus Avatar SDK is not compatible with the smooth pointer changes. It complains about being unable to attach an abstract class ObjectFollow; I attempted to fix the issue but could not get the controllers to properly follow the camera rig.

Uh damnit! Thanks a ton! The abstract (super)class `VRTK_ObjectFollow` can't be used on it's own now, you'll have to use one of the subclasses `VRTK_TransformFollow` or `VRTK_RigidbodyFollow`. I updated the PR to use `VRTK_TransformFollow`.

For the issue I think @thestonefox has to take over from here on. (He probably will chime in anyways, he is very busy.)

**Comment by bddckr** [comment] 2017-02-03 19:57
I wonder if #913 fixes this, too?

**Comment by thestonefox** [comment] 2017-02-03 19:58
Yeah good point it may well do

**Comment by thestonefox** [comment] 2017-02-03 19:58
actually no it wont, #913 is for the simple pointer only, the bezier pointer would be a different issue i'd expect

**Comment by bddckr** [comment] 2017-02-03 20:00
😞 Maybe that same fix could help here? I have no time to test it. 😞

**Comment by thestonefox** [comment] 2017-03-27 08:47
The "fix" for this as far as I can tell is to reduce the `BEAM_ADJUST_OFFSET` from `0.00001f` to `0.0001f`

It seems the problem exists when the terrain is set above a height of `255` so `256.0` and the problem occurs but `255.999999999` and no problem

**Comment by thestonefox** [comment] 2017-03-27 08:53
I bet it's fixed with https://github.com/thestonefox/VRTK/commit/56b63546790111fd329d644ba101ad036d7d96a3

I'm so confident I'm gonna close this issue!

**Closed by thestonefox** 2017-03-27 08:53 UTC
Labels: bug, ready
