### ISSUE TITLE
VRTK_Button - Button position bumps up after a Disable -> Enable

### ISSUE THREAD

**Issue by roskelld** [thestonefox/VRTK#1333] opened 2017-07-01 04:25 UTC
### Environment

 * Github
 * 3.2.0 95b8d62 
 * Unity 5.6.1f1
 * Vive
 * SteamVR 1.2.2

### Steps to reproduce

1. Load 025_Controls_Overview.unity
2. Move camera to face the selection of VRTK_Button GameObjects
2. Play the level from the editor (needed for next step)
3. In Hierarchy panel navigate to: ExampleWorldObjects > Buttons
4. In the Inspector Panel click on the Enable Box repeatedly to disable then re-enable the Buttons
<img width="1365" alt="default" src="https://user-images.githubusercontent.com/18073522/27759073-9ce5d89e-5de2-11e7-8eaa-609015718119.png">
5. Observe the two buttons that function on a vertical axis
<img width="1452" alt="afterabout10enables" src="https://user-images.githubusercontent.com/18073522/27759075-a2ef5292-5de2-11e7-9ade-d69961e4c9c5.png">

### Expected behavior

Buttons should re-enable in the same position prior to disabling.

### Current behavior

The buttons are recieving some sort of physics impulse on enable, that changes the resting position of the button and can cause it to fire the OnPushed() event.

I found that setting the Configureable Joint -> AutoConfigureConnectedAnchor to false 
<img width="410" alt="possiblefix" src="https://user-images.githubusercontent.com/18073522/27759078-c94fb86e-5de2-11e7-92a3-1997b7638da7.png">

**Comment by roskelld** [comment] 2017-07-01 07:33
I've been continuing to test this out by rolling back to VRTK from about a week ago, and to SteamVR 1.2.1 and I'm still seeing the same problems, so I don't believe it's due to a recent change.

Further to that I've been looking at the effects of 'Configurable Joint' 'Auto Configure Connected Anchor' and I've found that setting it to false causes the buttons to fall through the floor in a Release build. 

So it's not a solution to change this in order to prevent the buttons from moving between enable states.

**Comment by thestonefox** [comment] 2017-07-14 13:51
I think the auto anchor thing is the issue along with the constant force.

I've raised this PR https://github.com/thestonefox/VRTK/pull/1365

Which basically disables the auto anchor after the joint has been set up in the right position.

I've tested it in a build on example scene 25 and it seems to work ok.

**Comment by thestonefox** [comment] 2017-09-01 07:46
Previous PR did not fix the issue correctly.

**Comment by talothman** [comment] 2017-09-06 21:51
Issue seems to not have an effect on the 2 buttons attached to the plates. They both have `VRTK_Button`s but seem to function properly. 

![untitled](https://user-images.githubusercontent.com/5286101/30136240-06faf074-932c-11e7-93f5-e370c2963e00.png)

**Comment by thestonefox** [comment] 2017-09-07 06:10
@talothman The issue you're seeing has been fixed in 3.3.0-alpha (it was caused by a previous fix for this initial issue).

However, both the initial issue and the issue you're seeing are Unity bugs. I've reported both to Unity and they have confirmed they are bugs.

https://www.youtube.com/watch?v=8zIgZOxTH4c

https://www.youtube.com/watch?v=lbBEXzR59tY

**Comment by thestonefox** [comment] 2017-10-09 09:09
The new VRTK Button in this PR https://github.com/thestonefox/VRTK/pull/1550 doesn't have this problem

**Comment by thestonefox** [comment] 2017-10-26 08:01
Fixed with new controls

**Closed by thestonefox** 2017-10-26 08:01 UTC
Labels: bug, in review
