### ISSUE TITLE
Tunneling a Possible Addition?

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/VRTK#347] opened 2016-08-04 12:44 UTC
So during the upcoming **VRDC**, Ubi's _Olivier Palmieri_ is going to be talking about how they keep people from ralphing while playing their upcoming game _Eagle Flight_ (which does appear vomit inducing from gameplay vids) by utilizing 'blinders' when the player is near objects that would whizz by their peripheral vision such as buildings. Effectively '**Tunneling**' (I'm assuming), also used in _Adrift_

Anyway, any thoughts in implementing something like this? If not like the version in the linked video below, perhaps this could be similar to a geometry-based blink mechanic I've seen (no pun intended), using the geometry (Iris?) to converge at a point around the center of the players vision (should be a parameter that can be set to have larger or smaller 'blinders'). If that proves a bit cumbersome, perhaps just an alpha texture on a plane in front of the camera?

Here's Tunneling:
https://www.youtube.com/watch?v=lKnM5gC-XpY

...and a sample blink I randomly found:
https://www.youtube.com/watch?v=nDko7_iqXlQ

Thanks!

**Comment by xEvoGx** [comment] 2016-08-04 14:49
Ah perfect...

https://www.youtube.com/watch?v=lHzCmfuJYa4

...and yea that could be done rather easily on our own, but then again if it's so simple, it's one of those "_Features_" that can look very good for VRTK. :smile:

**Comment by xEvoGx** [comment] 2016-08-04 15:53
One more post for those interested! I didn't even consider using **Vignetting** to very easily create the Tunneling based on velocity!

http://fusedvr.com/does-this-help-your-vr-sickness-tutorial/

**Comment by thestonefox** [comment] 2016-08-04 16:39
someone go tell @fuseman to come and contribute to the repo :)

**Comment by HyppoNymous** [comment] 2016-08-16 21:22
+1 for tunneling options.

**Comment by dhagrow** [comment] 2016-11-17 18:39
Another +1.
Google Earth uses this as well, and it works great: https://vimeo.com/177549565.

**Comment by dantman** [comment] 2017-02-10 21:04
The biggest question we're going to probably have to answer is: What method of implement do we use?

From what I've seen there are several different methods of implementing tunnelling/vignetting:
* [2d cutout](http://www.cs.columbia.edu/2016/combating-vr-sickness/images/combating-vr-sickness.pdf)
* [Shader](https://github.com/SixWays/UnityVrTunnelling)
* [Vignette and chromatic aberration script](https://youtu.be/HZf2dp_sn-8)
* I'm not sure how Google Earth implements its version.

Which leaves us with key questions like: What are tradeoffs of each one? Is there any reason one is better than the others? Are there any performance tradeoffs that make one method a bad idea?
Sadly since most of the available information I can find comes in the form of research papers of people trying this for the first time as a concept and people doing tutorials on the first technique they found, there isn't really an answer to what kind of performance issues each method has.

Tradeoffs and advantages for each I can think of so far:
* The script method seems the simplest, a well known (built-in?) script, easily scriptable, and comes with adjustable parameters.
* Perhaps the cutout method in combination with a stencil shader could implement something that looks like the way google does it.
* I have no clue how the shader method works and I haven't heard much about it or what kind of compatibility or interfering side effects it could have.
* One comment mentions that the script method doesn't work for Daydream.
* The cutout method requires the addition of a physical 2d plane to the scene fixed in front of the camera, if you're not careful to apply layers and per-camera visibility correctly that object can show up in other camera views such as when doing mixed reality recording.

**Comment by mike-caputo** [comment] 2017-03-04 05:08
+1 This was implemented by Google's internal Daydream team at a GDC demo at GDC so I think it's definitely catching on.

**Comment by Poeticode** [comment] 2017-08-11 15:19
Has there been any more discussion on this? Tunneling is becoming very common in recent VR games that use any non-teleporting locomotion. I'm a fan of the script method that allows adjustable parameters, as it would help developers figure out what parameters work best to combat motion sickness while still retaining immersion in their games.

**Comment by thestonefox** [comment] 2017-09-27 10:55
Duplicate of https://github.com/thestonefox/VRTK/issues/222

**Closed by thestonefox** 2017-09-27 10:55 UTC
Labels: help wanted, new feature, w_feature
