### ISSUE TITLE
Interactable object loses its parent on enabling

### ISSUE THREAD

**Issue by rhduwe** [thestonefox/VRTK#918] opened 2017-02-06 14:17 UTC
### Environment

 * Github
 * Checked on VRTK 3.0.0 and latest master
 * Unity 5.51f1

### Steps to reproduce

* Launch the [project](https://drive.google.com/open?id=0B1sh71MexceEZWdsdlhuS1lhQ1k)
* Touch the sphere and press trigger to use it
* Manually toggle the "Parent" object disabled/enabled

### Expected behavior

Sphere stays in the hierarchy

### Current behavior

Sphere loses its parent and is moved to the scene root. 
There is no problem if sphere is grabbed and placed into the drop zone.

### Description

I've experienced this when using player items (children to the body) without grabbing them first. After player died and respawned, items no longer moved with the player.

I believe this is caused by `VRTK_InteractableObject::StopUsingInteractions()` setting `forcedDropped` flag, which then causes `LoadPreviousState()` to be called in `OnEnable()` method. And since `SavePreviousState` hasn't been called yet, parent gets set to `null` alongside with isKinematic and isGrabbable. This should be solved by calling SavePreviousState on script initialization.

**Comment by thestonefox** [comment] 2017-02-08 21:22
I can see what the issue is.

I'm not sure the best way to fix it at the moment.

**Comment by thestonefox** [comment] 2017-02-08 21:33
This PR fixes this specific issue

https://github.com/thestonefox/VRTK/pull/922

However, I'm not sure at the moment if this PR will break other edge cases

**Comment by thestonefox** [comment] 2017-02-12 22:47
Should be fixed now with https://github.com/thestonefox/VRTK/commit/866c93c053b46abe7ce549ed205665642a4a66c3

**Closed by thestonefox** 2017-02-12 22:47 UTC
Labels: bug
