### ISSUE TITLE
DontDestroyOnLoad Oculus SDK

### ISSUE THREAD

**Issue by D3m0n92** [thestonefox/VRTK#1290] opened 2017-06-15 23:20 UTC
**On latest version of VRTK of Git, when change scene, i receive 999+ error on console:**

**1)** MissingReferenceException: The object of type 'VRTK_TransformFollow' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
VRTK.VRTK_BasePointerRenderer.UpdatePointerOriginTransformFollow () (at Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs:316)
VRTK.VRTK_BasePointerRenderer.FixedUpdate () (at Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs:276)

**2)** MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
VRTK.VRTK_BasePointerRenderer.GetOrigin (Boolean smoothed) (at Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs:333)
VRTK.VRTK_StraightPointerRenderer.CastRayForward () (at Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs:188)
VRTK.VRTK_StraightPointerRenderer.UpdateRenderer () (at Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs:53)
VRTK.VRTK_Pointer.HandleEnabledPointer () (at Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs:325)
VRTK.VRTK_Pointer.Update () (at Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs:285)

**I use Unity 5.6.1p1 and, Oculus 1.15. No SteamVR.**

**Comment by bddckr** [comment] 2017-06-16 06:46
https://github.com/thestonefox/VRTK/issues/1145

**Comment by thestonefox** [comment] 2017-06-16 07:33
@bddckr is it ok to close this issue if it's a duplicate of #1145 ?

**Comment by bddckr** [comment] 2017-06-16 07:35
@thestonefox We could use one of these issues to remind us to fix "I want to use the same VRTK SDK Manager hierarchy in one scene and persist it properly". Some VRTK objects just don't know about the persist on load setting on the SDK Manager...

**Comment by thestonefox** [comment] 2017-06-16 07:37
may be worth just creating a new issue and then linking this one and #1145 to it?

**Comment by thestonefox** [comment] 2017-06-17 06:40
@bddckr do you want to raise the issue? I'm struggling to word it correctly. You don't need to follow the official template ;) just get something in so we can close this one :)

**Comment by bddckr** [comment] 2017-06-18 15:40
Will fix the mentioned issue with #1301.

**Comment by bddckr** [comment] 2017-06-22 12:27
Change of plans: `Persist on Load` issues when changing scenes will be done later, not part of #1301.

**Comment by bddckr** [comment] 2017-06-24 16:30
Superseded by #1316.

**Closed** 2017-06-24 16:54 UTC
