### ISSUE TITLE
Repository structure suggestion - submodules

### ISSUE THREAD

**Issue by camerongibbs85** [thestonefox/VRTK#1685] opened 2018-01-04 09:47 UTC
It would be great if the VRTK repository was structured the same as Unity-Technologies' [EditorVR](https://github.com/Unity-Technologies/EditorVR) repo so that it could be pulled in as a git [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules). This allows for composition of the version controlled VRTK repository within other people's version controlled projects.

You could consider extracting the VRTK Core code into its own repo and then creating a VRTK Examples Unity project that pulls the VRTK Core in as a submodule. This would allow decoupling of example updates from core updates and also serve as an example for others on how to setup submodules. It would also mean that a fresh VRTK Core checkout would be much smaller. 

I am happy to help make this happen if you think it is worth doing.

**Comment by thestonefox** [comment] 2018-01-04 09:49
This is a duplicate of other issues

e.g. 

https://github.com/thestonefox/VRTK/issues/1460

**Closed by thestonefox** 2018-01-04 09:49 UTC
