### ISSUE TITLE
Snap not working correctly

### ISSUE THREAD

**Issue by KospY** [thestonefox/VRTK#767] opened 2016-12-25 20:49 UTC
When we grab an object, the snap handle is rotating for an unknow reason.
When the object is not world aligned, the grabbed object will not be correctly aligned.

There is a function in VRTK_BaseGrabAttach "FlipSnapHandle", to invert the snap handle quaternion on start. Don't know what the purpose of it but disabling it fixed the problem.

**Comment by thestonefox** [comment] 2016-12-27 10:43
@KospY the inversion of the snap handles is done because the track object movement inverts the rotation when you grab something, meaning the snap handles are backwards.

If you're finding it your handles are being inverted then you may find your object forward is backwards.

**Comment by KospY** [comment] 2017-01-04 23:33
The handles are not inverted, they are not in the correct orientation.
This problem happen with the "VRTK_TrackObjectGrabAttach", this problem doesn't seem to happen with the classic child or fixed joint grab attach. To reproduce this bug, open the 014_Controller_SnappingObjectsOnGrab scene and set one of the item to track object. After that rotate the object beforce start and try to grab the object. It will get a wrong rotation (relative to the starting rotation I guess)

**Comment by thestonefox** [comment] 2017-01-05 10:56
@KospY ok so the issue is when the object is rotated in the scene. I'll look for a fix now.

**Comment by thestonefox** [comment] 2017-01-05 11:01
@KospY check out this pull request and see if it fixes your issue:

https://github.com/thestonefox/VRTK/pull/783

**Comment by KospY** [comment] 2017-01-05 20:11
@thestonefox It's working with the fix! Thanks!

**Comment by thestonefox** [comment] 2017-01-05 20:27
https://github.com/thestonefox/VRTK/pull/783 has now been merged into master

**Closed by thestonefox** 2017-01-05 20:27 UTC
Labels: bug
