### ISSUE TITLE
Snap Drop Zone Locked Out State

### ISSUE THREAD

**Issue by mattboy64** [thestonefox/VRTK#1049] opened 2017-03-24 21:31 UTC
There's an odd broken state the snap zones can get into where they can no longer snap new objects into them. The issue happens based on highlighting of the zone itself. Highlighting of a snapzone happens from `OnTriggerEnter()` and `OnTriggerExit()` calling `ToggleHighlight(Collider collider, bool state)`. The problem lies in the fact that the `ValidSnapObject()` function checks to see if an object is grabbed. That makes sense for highlighting of an object, but not as much for turning it off. If the holding object is forced out of a grab and moved by an external force before it can be placed (destroyed, shot out of hand, blows up, manually removed, etc.), ToggleHighlight will not pass ValidSnapObject and thus, will not deactivate the highlight and will not allow any other objects to be snapped there because currentValidSnapObject is never cleared out.

I solved it locally like this, but it's a hack at best:

```
        private void ToggleHighlight(Collider collider, bool state)
        {
            var ioCheck = ValidSnapObject(collider.gameObject, true);

            // E7_MAB we don't care about grabbing state on unhighlight
            if (state == false && ioCheck == null) {
                ioCheck = ValidSnapObject(collider.gameObject, false);
            }

            if (highlightObject && ioCheck)
            {
```

GitHub version of VRTK, maybe a month old, not sure
Unity 5.4.3

**Comment by Proktologe** [comment] 2017-03-26 00:03
There is a "similar" error. If the object enters more than one trigger-Zones ofSnapDropZone's then this will happen everytime when i release the object in a free SnapDropZone. I use 4 nearby SnapDropZone's when i put a object in one SnapDropZone a other SnapDropZone next to first will be invisible even if it is still free. Of course I want to stay visible.

**Comment by thestonefox** [comment] 2017-03-26 08:17
Can you add clear steps to reproduce the issue in the example scene.

I'm not sure I follow what the issue is here, or if there are different issues.

Also make sure to do this on the latest version of github master.

**Comment by Proktologe** [comment] 2017-03-26 10:18
Thanks for the info to make an update. My mentioned bug is fixed. But I noticed now:
- when i grab an (snapped) item from a SnapDropZone and this Item leave immediately the  SnapDropZone  whitout to trigger the SnapDropZone trigger, than the SnapDropZone-Highlight still be invisible.

**Comment by thestonefox** [comment] 2017-03-26 17:32
@Proktologe you have to provide steps to reproduce in an example scene for any issue otherwise people cannot see what the issue is for themselves and attempt to fix it.

**Comment by mattboy64** [comment] 2017-03-26 18:40
I'll make a test in the example scene to show the issues. I'll submit some videos as well showing how it's breaking on me.

**Comment by mattboy64** [comment] 2017-03-26 20:42
Here's a video showing what I do to lock out the snap drop zone. A zone is highlighted and upon release, since it's not a valid piece it's snapped back to it's original location and the snap drop zone becomes broken.

![snapbackbug](https://cloud.githubusercontent.com/assets/7003769/24335001/09b23490-122a-11e7-8573-6a630e26443f.gif)

**Comment by thestonefox** [comment] 2017-03-27 05:27
@mattboy64 I need steps to reproduce the issue in an example scene otherwise I cannot see what the problem is first hand.

You need to try and recreate the issue using the existing example scene and provide text step by step instructions for me to follow.

**Comment by telso2** [comment] 2017-04-14 02:29
@mattboy64  Hey Matt,

Are you still having the same problem? Im trying to destroy a game object that is being held in a snapdropzone and getting similar results. Once the gameobject is destroyed inside the snapdropzone, the snapdropszone becomes unusuable. 

Any ideas?

thanks,
tom

**Comment by mattboy64** [comment] 2017-04-14 03:06
@telso2 no, the above addition fixes the problem. I need to get @thestonefox some scripts to repro it himself and verify the fix should go into the mainline. I'll try and do that tonight.

**Comment by mattboy64** [comment] 2017-04-14 04:01
Attached is a script to repro this issue in example 41.

1. Attach the InvalidSnap.cs component to the red ball.

2. Place the red ball in the far left snap zone.

3. Script will force the ball back before a snap can happen.

4. Observe that no other object can be placed in the spot.

The above code change allows the Unhighlight function in the snap zone to set it back into a usable state since it see the object leave the trigger.

![image](https://cloud.githubusercontent.com/assets/7003769/25032783/046f8a26-208c-11e7-964d-8c6a378c19a8.png)


[InvalidSnap.zip](https://github.com/thestonefox/VRTK/files/921422/InvalidSnap.zip)

**Comment by mattboy64** [comment] 2017-04-14 04:17
@telso2 actually I think your problem is really similar to the one in #1052. I added a script to test your problem in there. It's probably a similar fix, but might require a little more since I don't know what state it'll be in since it's being destroyed and all.

**Comment by thestonefox** [comment] 2017-04-14 15:09
PR with resolution: https://github.com/thestonefox/VRTK/pull/1116

**Closed** 2017-04-15 15:21 UTC
Labels: bug, waiting for feedback
